import { useCallback, useRef, useState, type ReactNode } from 'react';
import { cx, useFieldId } from '../../utils';
import { Button } from '../Button';
import { Icon } from '../Icon';
import { AIMark, useDismiss } from './internal';

export interface AILabelProps {
  /** Figma: Label — the visible word. Keep it short: "AI", "AI generated", "Draft by AI". */
  label?: string;
  /** Figma: Size — xs 20 · sm 24 · md 28 */
  size?: 'xs' | 'sm' | 'md';
  /**
   * Figma: Style.
   * `chip` (default) — tinted pill with the gradient mark.
   * `inline` — mark and text, no fill; for message headers and table cells.
   * `icon` — the mark only; the label stays available to screen readers.
   */
  variant?: 'chip' | 'inline' | 'icon';
  /**
   * Figma: Explainability popover. Short, plain-language answer to "why am I seeing this?".
   * When set, the label becomes a button that opens the popover.
   */
  explanation?: ReactNode;
  /** Figma: Popover title — defaults to "About this AI content". */
  explanationTitle?: string;
  /** Model or agent that produced the content, shown in the popover footer. */
  model?: string;
  /** Figma: Edited — the person changed the AI content; the label reads "Edited" and loses the AI fill. */
  edited?: boolean;
  /** Figma: Revert to AI — shows a "Revert to AI" action in the popover (only while `edited`). */
  onRevert?: () => void;
  /** Which edge of the label the popover lines up with; use `end` near the right edge of a layout */
  align?: 'start' | 'end';
  /** Start with the popover open (docs and tests) */
  defaultOpen?: boolean;
  className?: string;
}

/**
 * Figma: AI label — marks AI-generated content and is the entry point to explainability.
 * With `explanation` it is a button with a non-modal popover (Esc and outside click close it).
 */
export function AILabel({ label = 'AI', size = 'sm', variant = 'chip', explanation, explanationTitle = 'About this AI content', model, edited = false, onRevert, align = 'start', defaultOpen, className }: AILabelProps) {
  const [open, setOpen] = useState(!!defaultOpen);
  const id = useFieldId();
  const wrap = useRef<HTMLSpanElement>(null);
  const trigger = useRef<HTMLButtonElement>(null);
  const close = useCallback(() => setOpen(false), []);
  useDismiss(open, close, [wrap], trigger);
  const text = edited ? 'Edited' : label;
  const iconSize = size === 'md' ? 16 : size === 'sm' ? 14 : 12;
  const classes = cx('at-ai-label', `at-ai-label--${size}`, `at-ai-label--${variant}`, edited && 'is-edited');
  const content = (
    <>
      {edited ? <Icon name="edit" size={iconSize} className="at-ai-label__edited" /> : <AIMark size={iconSize} />}
      {variant === 'icon' ? <span className="at-vh">{text}</span> : <span className="at-ai-label__text">{text}</span>}
    </>
  );
  const hasPopover = !!(explanation || model || (edited && onRevert));
  if (!hasPopover) {
    return <span className={cx(classes, className)} title={variant === 'icon' ? text : undefined}>{content}</span>;
  }
  return (
    <span ref={wrap} className={cx('at-ai-label-wrap', className)}>
      <button
        ref={trigger}
        type="button"
        className={classes}
        aria-expanded={open}
        aria-controls={`${id}-pop`}
        aria-label={`${text}: ${explanationTitle}`}
        onClick={() => setOpen(!open)}
      >
        {content}
        <Icon name="chevronDown" size={iconSize} className="at-ai-label__chev" />
      </button>
      {open ? (
        <div id={`${id}-pop`} role="dialog" aria-labelledby={`${id}-title`} className={cx('at-ai-pop', `at-ai-pop--${align}`)}>
          <div className="at-ai-pop__head">
            <AIMark size={18} />
            <p id={`${id}-title`} className="at-ai-pop__title">{explanationTitle}</p>
          </div>
          {explanation ? <div className="at-ai-pop__body">{explanation}</div> : null}
          {model || (edited && onRevert) ? (
            <div className="at-ai-pop__foot">
              {model ? <span className="at-ai-pop__model">Generated by <strong>{model}</strong></span> : <span />}
              {edited && onRevert ? (
                <Button hierarchy="outline" size="xs" iconLeading={<Icon name="undo" size={14} />} onClick={() => { onRevert(); setOpen(false); trigger.current?.focus(); }}>
                  Revert to AI
                </Button>
              ) : null}
            </div>
          ) : null}
        </div>
      ) : null}
    </span>
  );
}
