// Generates the Atomus shadcn registry source from the single sources:
//   react/src/components/*.tsx + react/src/utils.ts   → atomus/*.tsx, atomus/utils.ts      (registry:ui, registry:lib)
//   react/src/styles.css                              → each item's `css` (in @layer components)
//   css/atomus.css                                    → atomus-tokens `css`
//   shadcn/globals.css                                → atomus-theme `cssVars` + `css`
//   sites/docs/src/components/sections/*.tsx + sections.css → atomus/sections/*.tsx (registry:block) + website-parts
//   atomus/blocks/*.tsx + *.css (hand-written)        → app screen blocks
// and writes registry.json (the committed item index) plus .build/registry.json (with each item's CSS, for shadcn build).
// The copies in atomus/*.tsx, atomus/sections/ and .build/ are git-ignored build output.
// Run `node scripts/generate.mjs --check` to fail when the committed registry.json is stale.
//
// Usage: node scripts/generate.mjs [--check]
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, rmSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { cssToJson } from './css-to-json.mjs';
import { APP_BLOCKS, COMPONENTS, REGISTRY_URL, SITE } from './items.mjs';

const here = new URL('../', import.meta.url).pathname; // registry/
const root = join(here, '..'); // repo root
const out = join(here, 'atomus');
const check = process.argv.includes('--check');
const written = new Map(); // path → content

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const url = (name) => `${REGISTRY_URL}/${name}.json`;
const read = (p) => readFileSync(join(root, p), 'utf8');
const emit = (path, content) => written.set(join(here, path), content);
const header = (src) => `// Atomus 4.0 — ${src}. MIT licence, https://docs.atomus.io\n// Generated by the Atomus registry (registry/scripts/generate.mjs in github.com/StanVisionAgency/atomus); edit the source there.\n`;

// ---------------------------------------------------------------- exports of @stanvision/atomus-react

/** Maps every export of react/src/index.ts (values and types) to its registry item. */
const exportToItem = {};
const fileToItem = Object.fromEntries(COMPONENTS.map((c) => [c.file, c.name]));
for (const m of read('react/src/index.ts').matchAll(/export \{([^}]+)\} from '\.\/components\/(\w+)'/g)) {
  const item = fileToItem[m[2]];
  if (!item) throw new Error(`generate: react/src/components/${m[2]}.tsx is exported but not listed in scripts/items.mjs`);
  for (const name of m[1].split(',').map((s) => s.trim().replace(/^type\s+/, ''))) exportToItem[name] = item;
}
for (const f of readdirSync(join(root, 'react/src/components')).filter((f) => f.endsWith('.tsx') && !f.includes('.figma.') && !f.includes('.stories.'))) {
  if (!fileToItem[f.replace('.tsx', '')]) throw new Error(`generate: react/src/components/${f} has no registry item — add it to scripts/items.mjs`);
}

/** Rewrites `import { A, type B } from '<barrel>'` into one relative import per registry item. */
function splitBarrelImport(src, barrel, prefix) {
  const re = new RegExp(`import \\{([^}]+)\\} from '${barrel.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}';`, 'g');
  return src.replace(re, (_, names) => {
    const byItem = new Map();
    for (const raw of names.split(',').map((s) => s.trim()).filter(Boolean)) {
      const name = raw.replace(/^type\s+/, '');
      const item = exportToItem[name];
      if (!item) throw new Error(`generate: "${name}" is not exported by react/src/index.ts`);
      if (!byItem.has(item)) byItem.set(item, []);
      byItem.get(item).push(raw);
    }
    return [...byItem].map(([item, list]) => `import { ${list.join(', ')} } from '${prefix}${item}';`).join('\n');
  });
}

/** Registry items a TSX file imports through relative paths. */
function importedItems(src, map) {
  const items = new Set();
  for (const m of src.matchAll(/from '(\.{1,2}\/[\w-]+)'/g)) {
    const target = map(m[1]);
    if (target) items.add(target);
  }
  return [...items];
}

// ---------------------------------------------------------------- CSS slices

const styles = read('react/src/styles.css');
const cssSections = new Map();
{
  const headerRe = /^\/\* ([^\n—]+?) — Figma:/gm;
  const marks = [...styles.matchAll(headerRe)];
  cssSections.set('_common', styles.slice(0, marks[0].index));
  marks.forEach((m, i) => cssSections.set(m[1].trim(), styles.slice(m.index, marks[i + 1]?.index ?? styles.length)));
}
const usedSections = new Set(['_common']);
const componentCss = (names, source) => {
  const text = names.map((n) => {
    if (!cssSections.has(n)) throw new Error(`generate: no "/* ${n} — Figma: … */" section in react/src/styles.css`);
    usedSections.add(n);
    return cssSections.get(n);
  }).join('\n');
  return text.trim() ? { '@layer components': cssToJson(text, { source }) } : undefined;
};

// ---------------------------------------------------------------- items

const items = [];
const FONT_DEPS = ['@fontsource/inter', '@fontsource/roboto-mono'];
const FONT_IMPORTS = [...['300', '400', '500', '600', '700'].map((w) => `@fontsource/inter/${w}.css`), '@fontsource/roboto-mono/400.css', '@fontsource/roboto-mono/500.css'];
const docsFor = (lines) => lines.filter((l) => l !== null).join('\n');

// Tokens: css/atomus.css as is (custom properties for every theme, brand, radius and breakpoint + text styles).
items.push({
  name: 'atomus-tokens',
  type: 'registry:style',
  title: 'Atomus tokens',
  description: 'All Atomus design tokens as CSS custom properties: light and dark themes, the violet brand, sharp and round radius modes, tablet and mobile breakpoints, plus the Figma text-style classes.',
  extends: 'none',
  dependencies: FONT_DEPS,
  css: {
    // Same families as the Figma file: @fontsource/* declare "Inter" and "Roboto Mono", the names the tokens use.
    ...Object.fromEntries(FONT_IMPORTS.map((f) => [`@import "${f}"`, {}])),
    ...cssToJson(read('css/atomus.css'), { source: 'css/atomus.css' }),
  },
  docs: docsFor([
    'Atomus tokens were added to your CSS file (unlayered custom properties on :root), with the Inter and Roboto Mono fonts.',
    'Switch themes with attributes on <html> or any element: data-theme="dark", data-brand="violet", data-radius="round" | "sharp".',
    'Use semantic tokens only, e.g. var(--color-text-primary), var(--spacing-xl), var(--radius-md). Reference: https://docs.atomus.io/code/tokens/',
  ]),
  categories: ['tokens'],
  meta: { source: 'css/atomus.css', page: `${SITE}/code/tokens/` },
});

// Theme: shadcn/ui variables mapped to Atomus semantic tokens (shadcn/globals.css).
{
  const g = read('shadcn/globals.css');
  const block = g.match(/^:root, \.dark, \[data-theme\], \[data-brand\] \{([\s\S]*?)\n\}/m);
  const theme = g.match(/^@theme inline \{([\s\S]*?)\n\}/m);
  const variant = g.match(/^@custom-variant dark (.+);$/m);
  if (!block || !theme || !variant) throw new Error('generate: shadcn/globals.css changed shape — update the atomus-theme section of generate.mjs');
  const decls = (s) => Object.fromEntries([...s.matchAll(/--([\w-]+):\s*([^;]+);/g)].map((m) => [m[1], m[2].trim()]));
  const vars = decls(block[1]);
  // shadcn adds `--color-<x>: var(--<x>)` to @theme inline for every colour variable itself; keep only the others.
  const themeVars = Object.fromEntries(Object.entries(decls(theme[1])).filter(([k, v]) => v !== `var(--${k.replace(/^color-/, '')})`));
  items.push({
    name: 'atomus-theme',
    type: 'registry:theme',
    title: 'Atomus theme for shadcn/ui',
    description: 'Maps the shadcn/ui variables (background, primary, muted, border, ring, sidebar, chart …) to Atomus semantic tokens, so shadcn/ui components follow the Atomus theme, brand and radius modes.',
    registryDependencies: [url('atomus-tokens')],
    cssVars: { theme: themeVars, light: vars, dark: vars },
    css: {
      // Re-declared on themed elements so a nested data-theme / data-brand switch recomputes them (cssVars only write :root and .dark).
      ':root, .dark, [data-theme], [data-brand]': vars,
      '@layer base': { '*': { '@apply border-border outline-ring/50': {} }, body: { '@apply bg-background text-foreground': {} } },
    },
    docs: docsFor([
      'shadcn/ui variables now point at Atomus tokens. Dark mode: set data-theme="dark" (or the .dark class) on <html>.',
      `For Tailwind's dark: variant to follow data-theme too, use: @custom-variant dark ${variant[1]};`,
      'Brand and shape: data-brand="violet", data-radius="round" | "sharp". Docs: https://docs.atomus.io/code/shadcn/',
    ]),
    categories: ['theme'],
    meta: { source: 'shadcn/globals.css', page: `${SITE}/code/shadcn/` },
  });
}

// Shared helpers + the component CSS that every component uses (font family, .at-icon).
emit('atomus/utils.ts', header('from react/src/utils.ts') + read('react/src/utils.ts'));
items.push({
  name: 'atomus-utils',
  type: 'registry:lib',
  title: 'Atomus utils',
  description: 'Helpers the Atomus components share (cx, useFieldId, useOutsideClick) and their base CSS. Installed automatically with any component.',
  registryDependencies: [url('atomus-tokens')],
  files: [{ path: 'atomus/utils.ts', type: 'registry:lib', target: 'components/atomus/utils.ts' }],
  css: componentCss(['_common'], 'react/src/styles.css'),
  categories: ['lib'],
  meta: { source: 'react/src/utils.ts' },
});

// One registry:ui item per component file.
for (const c of COMPONENTS) {
  let src = read(`react/src/components/${c.file}.tsx`);
  src = src.replace(/from '\.\.\/utils'/g, "from './utils'");
  src = src.replace(/from '\.\/(\w+)'/g, (m, f) => {
    if (f === 'utils') return m;
    if (!fileToItem[f]) throw new Error(`generate: ${c.file}.tsx imports ./${f}, which has no registry item`);
    return `from './${fileToItem[f]}'`;
  });
  const path = `atomus/${c.name}.tsx`;
  emit(path, header(`${c.title} from @stanvision/atomus-react (react/src/components/${c.file}.tsx)`) + src);
  const deps = new Set(['atomus-utils', ...importedItems(src, (p) => (p === './utils' ? null : p.slice(2))), ...(c.cssDeps ?? [])]);
  items.push({
    name: c.name,
    type: 'registry:ui',
    title: c.title,
    description: c.description,
    registryDependencies: [...deps].map(url),
    files: [{ path, type: 'registry:ui', target: `components/atomus/${c.name}.tsx` }],
    css: componentCss(c.css, `react/src/styles.css (${c.title})`),
    docs: docsFor([
      `import { ${c.exports.join(', ')} } from "@/components/atomus/${c.name}";`,
      `Props mirror the Figma component properties. Usage and React API: ${SITE}/${c.page}/`,
      'Prefer the npm package instead? npm i @stanvision/atomus-react and import from "@stanvision/atomus-react".',
    ]),
    categories: ['component'],
    meta: { source: `react/src/components/${c.file}.tsx`, exports: c.exports, page: `${SITE}/${c.page}/` },
  });
}
for (const name of cssSections.keys()) if (!usedSections.has(name)) throw new Error(`generate: react/src/styles.css section "${name}" is not used by any item in scripts/items.mjs`);

// App screen blocks (hand-written in atomus/blocks/).
for (const b of APP_BLOCKS) {
  const path = `atomus/blocks/${b.name}.tsx`;
  const src = readFileSync(join(here, path), 'utf8');
  const imported = importedItems(src, (p) => (p.startsWith('../') ? p.slice(3) : p.slice(2)));
  const missing = imported.filter((i) => !b.uses.includes(i));
  if (missing.length) throw new Error(`generate: ${path} imports ${missing.join(', ')} — add them to its "uses" in scripts/items.mjs`);
  const cssPath = join(here, `atomus/blocks/${b.name}.css`);
  const component = b.name.replace(/(^|-)(\w)/g, (_, __, ch) => ch.toUpperCase());
  items.push({
    name: b.name,
    type: b.type ?? 'registry:block',
    title: b.title,
    description: b.description,
    registryDependencies: b.uses.map(url),
    files: [{ path, type: 'registry:component', target: `components/atomus/blocks/${b.name}.tsx` }],
    css: existsSync(cssPath) ? { '@layer components': cssToJson(readFileSync(cssPath, 'utf8'), { source: `atomus/blocks/${b.name}.css` }) } : undefined,
    docs: docsFor([
      `import { ${component} } from "@/components/atomus/blocks/${b.name}";`,
      'Replace the sample data with yours; every colour, space and radius is an Atomus token. Rules: https://docs.atomus.io/ai/rules/',
    ]),
    categories: ['block', 'app'],
    meta: { kind: 'app', component },
  });
}

// Website sections (from the docs previews).
const sectionsDir = 'sites/docs/src/components/sections';
const sectionIndex = read(`${sectionsDir}/index.ts`);
const SECTIONS = [...sectionIndex.matchAll(/^\s+(?:'([^']+)': (\w+)|(\w+)),$/gm)].map((m) => ({ title: m[1] ?? m[3], file: m[2] ?? m[3] }));
if (SECTIONS.length < 30) throw new Error(`generate: found ${SECTIONS.length} sections in ${sectionsDir}/index.ts, expected 30`);
const sectionItem = (file) => kebab(file);
const toRegistrySection = (src) =>
  splitBarrelImport(src, '../../../../../react/src', '../')
    .replace(/from '\.\/parts'/g, "from './parts'")
    .replace(/from '\.\/(\w+)'/g, (m, f) => (f === 'parts' ? m : `from './${sectionItem(f)}'`));

{
  // Shared parts + the section CSS (everything below "Section building blocks" in the docs' sections.css).
  const parts = toRegistrySection(read(`${sectionsDir}/parts.tsx`));
  emit('atomus/sections/parts.tsx', header(`website section parts (${sectionsDir}/parts.tsx)`) + parts);
  const scss = read('sites/docs/src/styles/sections.css');
  const start = scss.indexOf('/* Section building blocks');
  if (start < 0) throw new Error('generate: "/* Section building blocks" marker missing in sites/docs/src/styles/sections.css');
  const pageCss = scss
    .slice(start)
    // The docs preview is a scaled canvas with container queries; real pages use the viewport breakpoints.
    .replace(/@container ws \(/g, '@media (')
    // .ws-root is the docs canvas; on a page the section roots carry its base styles.
    .replace(/\.ws-root/g, ':where(.ws-section, .ws-header, .ws-footer, .ws-auth)');
  items.push({
    name: 'website-parts',
    type: 'registry:component',
    title: 'Website section parts',
    description: 'Layout building blocks for the Atomus website sections (Section, Head, Img, logo and brand marks) and the responsive section CSS. Installed with every website section.',
    registryDependencies: importedItems(parts, (p) => p.slice(3)).map(url),
    files: [{ path: 'atomus/sections/parts.tsx', type: 'registry:component', target: 'components/atomus/sections/parts.tsx' }],
    css: { '@layer components': cssToJson(pageCss, { source: 'sites/docs/src/styles/sections.css' }) },
    categories: ['website'],
    meta: { source: `${sectionsDir}/parts.tsx` },
  });
}

for (const s of SECTIONS) {
  const name = sectionItem(s.file);
  const src = toRegistrySection(read(`${sectionsDir}/${s.file}.tsx`));
  const path = `atomus/sections/${name}.tsx`;
  emit(path, header(`website section "${s.title}" (${sectionsDir}/${s.file}.tsx)`) + src);
  const anatomy = [...(src.match(/export const anatomy = \[([\s\S]*?)\];/)?.[1] ?? '').matchAll(/'((?:[^'\\]|\\.)*)'/g)].map((m) => m[1].replace(/\\'/g, "'"));
  const deps = importedItems(src, (p) => (p.startsWith('../') ? p.slice(3) : p.slice(2) === 'parts' ? 'website-parts' : p.slice(2)));
  const description = `Website section: ${s.title}. ${anatomy.length ? `${anatomy.join('; ')}.` : ''}`.replace(/\.\.$/, '.');
  items.push({
    name,
    type: 'registry:block',
    title: s.title,
    description,
    registryDependencies: [...new Set(['website-parts', ...deps])].map(url),
    files: [{ path, type: 'registry:component', target: `components/atomus/sections/${name}.tsx` }],
    docs: docsFor([
      `import ${s.file} from "@/components/atomus/sections/${name}";`,
      'Replace the sample copy and images with yours. Layout and type switch at the Atomus tablet (1023px) and mobile (767px) breakpoints.',
      `Preview and Figma variants: ${SITE}/website-sections/#${s.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`,
    ]),
    categories: ['block', 'website'],
    meta: { kind: 'website', section: s.title, component: s.file },
  });
}

// The whole system: tokens, shadcn theme, fonts, base styles and the npm packages.
items.unshift({
  name: 'atomus',
  type: 'registry:base',
  title: 'Atomus design system',
  description: 'The whole Atomus 4.0 system for a shadcn project: tokens (light/dark, brand and radius modes, breakpoints), the shadcn/ui theme mapped to Atomus, Inter and Roboto Mono, base styles, and the @stanvision/atomus-react and @stanvision/atomus-tokens packages.',
  dependencies: ['@stanvision/atomus-react', '@stanvision/atomus-tokens'],
  registryDependencies: [url('atomus-theme'), url('atomus-utils')],
  css: {
    '@layer base': {
      body: { 'font-family': 'var(--font-family-body)', color: 'var(--color-text-secondary)', background: 'var(--color-bg-primary)', '-webkit-font-smoothing': 'antialiased' },
      'code, kbd, pre, samp': { 'font-family': '"Roboto Mono", ui-monospace, monospace' },
      ':focus-visible': { outline: '2px solid var(--color-border-focus)', 'outline-offset': '2px' },
    },
  },
  docs: docsFor([
    'Atomus is installed: tokens, the shadcn/ui theme, fonts and base styles are in your CSS file.',
    'Components: add them as source with `npx shadcn@latest add @atomus/button` (see https://docs.atomus.io/ai/registry/) or import them from "@stanvision/atomus-react" (and import "@stanvision/atomus-react/styles.css" once).',
    'Agents: read https://docs.atomus.io/llms.txt and the rules at https://docs.atomus.io/ai/rules/',
  ]),
  categories: ['base'],
  meta: { page: `${SITE}/` },
});

const registry = {
  $schema: 'https://ui.shadcn.com/schema/registry.json',
  name: 'atomus',
  homepage: SITE,
  items: items.map(({ css, ...it }) => ({ ...it, author: 'StanVision (https://stan.vision)', ...(css ? { css } : {}) })),
};
// registry.json (committed): the item index — names, types, descriptions, docs, dependencies and files. It is what
// the docs (RegistryActions.astro) and reviewers read. .build/registry.json (git-ignored) adds each item's `css`,
// generated from the single sources above; scripts/build.mjs runs `shadcn build` on it.
const lean = { ...registry, items: registry.items.map(({ css, ...it }) => it) };
emit('registry.json', `${JSON.stringify(lean, null, 2)}\n`);
emit('.build/registry.json', `${JSON.stringify(registry, null, 2)}\n`);

// ---------------------------------------------------------------- write or check

let stale = [];
const keep = new Set([...written.keys()]);
for (const [path, content] of written) {
  // Only registry.json is committed; the source copies and .build/ are written by every build.
  if (check && path !== join(here, 'registry.json')) continue;
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === content) continue;
  if (check) stale.push(relative(here, path));
  else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
}
// Remove generated files that no longer have a source (component and section copies only, never blocks/).
for (const dir of check ? [] : ['atomus', 'atomus/sections']) {
  if (!existsSync(join(here, dir))) continue;
  for (const f of readdirSync(join(here, dir), { withFileTypes: true })) {
    const p = join(here, dir, f.name);
    if (f.isFile() && !keep.has(p)) {
      if (check) stale.push(`${relative(here, p)} (orphan)`);
      else rmSync(p);
    }
  }
}
if (check && stale.length) {
  console.error(`registry: ${stale.length} generated file(s) are stale — run \`npm run generate\` in registry/:\n  ${stale.join('\n  ')}`);
  process.exit(1);
}
console.log(`registry: ${items.length} items (${COMPONENTS.length} components, ${APP_BLOCKS.length} app blocks, ${SECTIONS.length} website sections)${check ? ' — up to date' : ''}`);
